spring.application.name=ErrorFreeText
# Подключение к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/error_free_text
spring.datasource.username=postgres
spring.datasource.password=root

# Драйвер PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Логирование SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE